all: ex1 ex2 ex3

ex1: ex1_linked_list.cpp
	g++ ex1_linked_list.cpp -o ex1

ex2: ex2_linked_list.cpp
	g++ ex2_linked_list.cpp -o ex2

ex3: ex3_linked_list.cpp
	g++ ex3_linked_list.cpp -o ex3

clean:
	del ex1.exe ex2.exe ex3.exe