all: ex1_stack ex2_stack ex3_stack

ex1_stack: ex1_stack.cpp
	g++ ex1_stack.cpp -o ex1_stack

ex2_stack: ex2_stack.cpp
	g++ ex2_stack.cpp -o ex2_stack

ex3_stack: ex3_stack.cpp
	g++ ex3_stack.cpp -o ex3_stack

clean:
	del ex1_stack.exe ex2_stack.exe ex3_stack.exe
