all: ex1_queue ex2_queue ex3_queue

ex1_queue: ex1_queue.cpp
	g++ ex1_queue.cpp -o ex1_queue

ex2_queue: ex2_queue.cpp
	g++ ex2_queue.cpp -o ex2_queue

ex3_queue: ex3_queue.cpp
	g++ ex3_queue.cpp -o ex3_queue

clean:
	del ex1_queue.exe ex2_queue.exe ex3_queue.exe
