all: ex1_linked_list ex2_linked_list ex3_linked_list

ex1_linked_list: ex1_linked_list.cpp
	g++ ex1_linked_list.cpp -o ex1_linked_list

ex2_linked_list: ex2_linked_list.cpp
	g++ ex2_linked_list.cpp -o ex2_linked_list

ex3_linked_list: ex3_linked_list.cpp
	g++ ex3_linked_list.cpp -o ex3_linked_list

clean:
	del ex1_linked_list.exe ex2_linked_list.exe ex3_linked_list.exe